### ISSUE TITLE
Bug in accept application story

### ISSUE THREAD

**Issue by GioGiunta2606** [s292567/ThesisApplication#18]
When a professor accept or reject an application made from a student it's better to remove the buttons and put something with the new status of the application, for example a badge with accepted or reject. In that way the professor can't do one operation more than one time.

**Comment by NicolaGasparotto** [comment]
the functioning logic that during the demo was bugged was already working and it's the following one:
- when a student application is declined the student application is removed from the list
- when a student application is accepted the proposal is removed and also all the students

These behaviour are due to the specification imposed in the faq that when a proposal has an accepted student this one is archived.
And also to maintain a cleaner ui the list of declined students into a proposal are not showned
